### PR TITLE
V0.40

### PR DESCRIPTION
**Pull request by miceno**
Hi.

This is my very second pull, so please, accept my apologies in case I don't proceed properly :)

I am here by providing a fix for #25 (my own issue ;) to include new options to control the tiler to link to.

I have also updated the README.md to ammend some mistakes in the examples and include description for new options of #25.

### CODE REVIEW

**Comment by xavijam** [comment]
Thanks miceno! Absolutely useful, accepting pull request. :)

**Comment by xavijam** [comment]
Oops, there has been an error with the pull request. Github went crazy.

**Comment by miceno** [comment]
And... then did it succeed?

**Comment by xavijam** [comment]
Finally implemented by hand, now it is released. I have just written a post in our mailing list talking about the changes:

https://groups.google.com/forum/#!topic/cartodb/L7BFLzxg-uw

Hope you find it useful.

Thanks for your feedback and sorry again for the failed pull request.

**Pull request closed without merging**
